myshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url, include
# 配置media下的图片
# https://blog.csdn.net/u012561176/article/details/86063128
from django.views.static import serve
from myshop.settings import MEDIA_ROOT
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),    
    url(r'^stationadmin/', include('stationAdmin.urls')),
    url(r'^seller/', include('seller.urls')),
    url(r'index/', views.index, name="index"),
]

seller/urls.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from django.conf.urls import url

from . import views

app_name = 'seller'
urlpatterns = [
    url(r"register", views.sellerRegister, name="seller_register"),
    url(r"login", views.sellerLogin, name="seller_login"),
    url(r"persional/(\d+)", views.sellerPersional, name="seller_persional"),
    url(r"goodslist/(\d+)", views.sellerAllGoods, name="seller_allGoods"),
    url(r"addgoods/(\d+)", views.sellerAddGoods, name="seller_addGoods"),
    url(r"addtag/(\d+)", views.sellerAddTag, name="seller_addTag"),
    url(r"addpreferential/(\d+)", views.sellerAddPreferential, name="seller_addPreferential"),
    url(r"addtypes/(\d+)", views.sellerAddTypes, name="seller_addTypes"),
    url(r"goodsdetail/(\d+)", views.sellerGoodsDetail, name="seller_goodsDetail"),
    url(r"goodschangemessage/(\d+)", views.sellerGoodsChangeMessage, name="seller_goodsChangeMessage"),
]

seller/models.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from django.db import models
from django.utils import timezone

# Create your models here.
class Seller(models.Model):
    name = models.CharField(max_length=20)
    sex = models.CharField(max_length=10)
    age = models.CharField(max_length=10)
    phone = models.CharField(max_length=11)
    password = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    registerDate = models.DateField(default=timezone.now)
    photo = models.ImageField(upload_to="media/%Y/%m/%d", blank=True, null=True)
    
    class Meta:
        ordering = ('id',)
        index_together = (('id', 'name', 'email'),)
        
    def __str__(self):
        return self.name
    
class Goods(models.Model):
    name = models.CharField(max_length=50) # 货物名称
    tag = models.ForeignKey('Tag', on_delete=models.DO_NOTHING) # 货物标签
    types = models.ForeignKey('Types', on_delete=models.DO_NOTHING) # 货物分类
    price =  models.FloatField()# 货物价格
    number = models.IntegerField() # 货物库存量
    owner = models.ForeignKey('Seller', on_delete=models.DO_NOTHING) # 货物拥有者
    color = models.CharField(max_length=10) # 货物颜色
    time = models.DateField(default=timezone.now) # 货物的上架时间
    describe = models.TextField(max_length=500) # 货物描述
    goodsImage = models.ImageField(upload_to="media/%Y/%m/%d", blank=True, null=True) # 货物图片
    isPreferential = models.CharField(max_length=1, default='否') # 是否打折(值为是或否)
    
    class Meta:
        ordering = ('id',)
        index_together = (('id', 'name'),)
        
    def __str__(self):
        return self.name    
    
class Tag(models.Model):
    name = models.CharField(max_length=10)
    
    class Meta:
        ordering = ('id',)
        index_together = (('id', 'name'),)
        
    def __str__(self):
        return self.name    
    
class Types(models.Model):
    name = models.CharField(max_length=10)
    
    class Meta:
        ordering = ('id',)
        index_together = (('id', 'name'),)
        
    def __str__(self):
        return self.name    
  
class Preferential(models.Model): # 优惠券
    seller = models.ForeignKey('Seller', on_delete=models.DO_NOTHING) # 是哪家店铺发布的优惠券
    goods = models.ForeignKey('Goods', on_delete=models.DO_NOTHING) # 是对那种商品打折
    preferential_type = models.IntegerField() # 优惠类型（满减1、打几折2、满足多少后打几折3）
    enoughNumber =  models.FloatField() # 如果是满减，则此填满多少，不是则填0
    minusNumber =  models.FloatField() # 如果是满减，则此填减多少，不是则填0
    discount =  models.FloatField() # 如果是打折，则此填打折小数（打8折填写0.8），不是则填写1
    cutOffDatetime = models.DateField() # 优惠券的截至日期
    describe = models.TextField(max_length=500) # 优惠券描述
    
    class Meta:
        ordering = ('id',)
        index_together = (('id',),)
        
    def __str__(self):
        return self.describe
    
    

seller/forms.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from django import forms
from .models import Tag, Types, Seller, Preferential, Goods

class RegisterForm(forms.Form):
    username = forms.CharField(min_length=2)
    password = forms.CharField(widget=forms.PasswordInput)
    sex = forms.fields.ChoiceField(
        choices=((1, "男"),(2, "女"),),
        initial=1,
        widget=forms.widgets.RadioSelect    
    )
    age = forms.CharField()
    phone = forms.CharField(max_length=11)
    email = forms.EmailField(required=True)
    address = forms.CharField(max_length=255)
    photo = forms.FileField(required=False)
    
class LoginForm(forms.Form):
    phone = forms.CharField(max_length=11)
    password = forms.CharField(widget=forms.PasswordInput)
    
class AddGoodsForm(forms.Form):
    name = forms.CharField()
    tagResults = Tag.objects.filter()
    typesResults = Types.objects.filter()
    tags = []
    typess = []
    # 得到所有的标签数据并转换为元组
    if len(tagResults) > 0: # 判断是否为空
        for i in range(0, len(tagResults)):
            result = tagResults[i]
            tag = [result.id, result.name]
            tag = tuple(tag)
            tags.append(tag)
        tags = tuple(tags)
        tag = forms.fields.ChoiceField(
                choices=tags,
                widget=forms.widgets.Select()
            )        
    else:
        pass
    # 得到所有的类型数据并转换为元组
    if len(typesResults) > 0: # 判断是否为空
        for i in range(0, len(typesResults)):
            result = typesResults[i]
            types = [result.id, result.name]
            types = tuple(types)
            typess.append(types)
        typess = tuple(typess)
        types = forms.fields.ChoiceField(
                choices=typess,
                widget=forms.widgets.Select()
            )
    else:
        pass
    # price = forms.CharField(widget=forms.FloatField)
    price = forms.FloatField()
    number = forms.IntegerField()
    color = forms.CharField()
    describe = forms.CharField(widget=forms.Textarea)
    goodsImage = forms.FileField(required=False)
    isPreferential = forms.fields.ChoiceField(
        choices=((1, "是"), (2, "否")),
        initial=2,
        widget=forms.widgets.RadioSelect()
    )

class AddTagForm(forms.Form):
    name = forms.CharField()

class AddTypesForm(forms.Form):
    name = forms.CharField()
    
 
class AddPreferentialForm(forms.Form):
    goodsResults = Goods.objects.filter()
    goodses = []
    if len(goodsResults) > 0: # 判断是否为空
        for i in range(0, len(goodsResults)):
            result = goodsResults[i]
            goods1 = [result.id, result.name]
            goods1 = tuple(goods1)
            goodses.append(goods1)
        goodses = tuple(goodses)
        goods = forms.fields.ChoiceField(
            choices=goodses,
                widget=forms.widgets.Select()
        )
    else:
            pass
    preferential_type = forms.fields.ChoiceField(
        choices=((1, "满减"), (2, "打折"), (3, "满额后打折")),
        initial=1,
        widget=forms.widgets.RadioSelect()
    )
    enoughNumber = forms.FloatField()
    minusNumber = forms.FloatField()
    discount = forms.FloatField()
    cutOffDatetime = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    describe = forms.CharField(widget=forms.Textarea)

seller/views.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import RegisterForm, LoginForm, AddGoodsForm, AddTagForm, AddTypesForm, AddPreferentialForm
from .models import Seller, Tag, Types, Goods, Preferential

# Create your views here.
def sellerRegister(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            password = cd['password']
            if cd['sex'] == 1:
                sex = '男'
            else:
                sex = '女'
            age = cd['age']
            phone = cd['phone']
            email = cd['email']
            address = cd['address']
            photo = request.FILES.get("photo")
            seller = Seller()
            seller.name = username
            seller.password = password
            seller.sex = sex
            seller.age = age
            seller.phone = phone
            seller.email = email
            seller.address = address
            seller.photo = photo
            seller.save()
            return HttpResponse("success")
        else:
            return HttpResponse("Invalid register")
    
    else:
        form = RegisterForm()
        
    return render(request, 'seller/register.html', {"form": form})

def sellerLogin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)    
        if form.is_valid():
            cd = form.cleaned_data
            phone = cd['phone']
            password = cd['password']
            sellers = Seller.objects.filter(phone=phone)
            if len(sellers) == 0:
                return HttpResponse("账号不存在！")
            else:
                seller = sellers[0]
                if password == seller.password:
                    # return HttpResponse("登录成功！")
                    response = redirect('/seller/persional/' + str(seller.id))
                    #设置cookie username *过期时间为12小时， 设置一个星期为：7*24*3600
                    response.set_cookie('username', seller, max_age=1*12*3600)
                    request.session['islogin'] = True
                    return response
                else:
                    return HttpResponse("密码错误！")
            
    else:
        form = LoginForm()
        
    return render(request, 'seller/login.html', {"form": form})

def sellerPersional(request, id):
    if request.session.has_key('islogin'): # 检测是否登录
        sellers = Seller.objects.filter(id=id)
        seller = sellers[0]
        data = {}
        
        data['seller'] = seller
        
        return render(request, 'seller/persional.html', data)
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form}) 
    
def sellerAllGoods(request, id):
    if request.session.has_key('islogin'): # 检测是否登录
        goodses = Goods.objects.filter(owner_id=id)
        data = {}
        
        data['goodses'] = goodses
        
        return render(request, 'seller/goodslist.html', data)
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form})    
    
def sellerAddGoods(request, id):
    if request.session.has_key('islogin'): # 检测是否登录
        if request.method == "POST":
            form = AddGoodsForm(request.POST)    
            if form.is_valid():
                cd = form.cleaned_data
                # 提取从表单中传过来的数据并进行处理
                name = cd['name']
                formTag = cd['tag']
                formTypes = cd['types']
                price = cd['price']
                number = cd['number']
                color = cd['color']
                describe = cd['describe']
                print(describe)
                tag = Tag.objects.filter(id=formTag)[0]
                types = Types.objects.filter(id=formTypes)[0]
                owner = Seller.objects.filter(id=id)[0]
                goodsImage = request.FILES.get("goodsImage")
                # 创建数据并插入数据库
                goods = Goods()
                goods.name = name
                goods.tag = tag
                goods.types = types
                goods.price = price
                goods.number = number
                goods.owner = owner
                goods.color = color
                goods.describe = describe
                print("des:", goods.describe)
                goods.goodsImage = goodsImage
                goods.save()
        else:
            form = AddGoodsForm()
            
        return render(request, 'seller/addgoods.html', {"form": form})
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form}) 
    
def sellerAddTag(request, id):
    if request.session.has_key('islogin'): # 检测是否登录
        if request.method == "POST":
            form = AddTagForm(request.POST)    
            if form.is_valid():
                cd = form.cleaned_data
                name = cd['name']
                tag = Tag()
                tag.name = name
                tag.save()
        else:
            form = AddTagForm()
            
        return render(request, 'seller/addtag.html', {"form": form})
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form}) 
    
def sellerAddTypes(request, id):
    if request.session.has_key('islogin'): # 检测是否登录
        if request.method == "POST":
            form = AddTypesForm(request.POST)    
            if form.is_valid():
                cd = form.cleaned_data
                name = cd['name']
                types = Types()
                types.name = name
                types.save()
        else:
            form = AddTypesForm()
            
        return render(request, 'seller/addtypes.html', {"form": form})
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form}) 
    
def sellerGoodsDetail(request, id):
    if request.session.has_key('islogin'): # 检测是否登录
        goods = Goods.objects.get(id=id)
        data = {}
        data['goods'] = goods
        if goods.isPreferential == '是':
            seller = Seller.objects.get(id=goods.owner_id)
            preferentials = Preferential.objects.filter(seller_id=seller.id).filter(goods_id=goods.id)
            data['preferentials'] = preferentials
        
        return render(request, 'seller/goodsdetail.html', data)
    
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form})     
    
def sellerGoodsChangeMessage(request, id):
    if request.session.has_key('islogin'):
        if request.method == "POST":
            form = AddGoodsForm(request.POST)    
            if form.is_valid():
                goods = Goods.objects.get(id=id)                
                cd = form.cleaned_data
                # 提取从表单中传过来的数据并进行处理
                name = cd['name']
                formTag = cd['tag']
                formTypes = cd['types']
                price = cd['price']
                number = cd['number']
                color = cd['color']
                describle = cd['describle']
                print(describle)
                tag = Tag.objects.filter(id=formTag)[0]
                types = Types.objects.filter(id=formTypes)[0]
                goodsImage = request.FILES.get("goodsImage")
                # 创建数据并插入数据库
                goods.name = name
                goods.tag = tag
                goods.types = types
                goods.price = price
                goods.number = number
                goods.color = color
                goods.describle = describle
                print("des:", goods.describe)
                goods.goodsImage = goodsImage
                goods.save()
        else:
            form = AddGoodsForm()
            
        return render(request, 'seller/goodschangemessage.html', {"form": form})
    
    else:
        form = LoginForm()
        return render(request, 'seller/login.html', {"form": form})
    
def sellerAddPreferential(request, id): # 传入的是seller的id
    if request.session.has_key('islogin'):
        if request.method == "POST":
            form = AddPreferentialForm(request.POST)    
            if form.is_valid():
                cd = form.cleaned_data
                goods = Goods.objects.get(id=cd['goods'])
                preferential_type = cd['preferential_type']
                enoughNumber = cd['enoughNumber']
                minusNumber = cd['minusNumber']
                discount = cd['discount']
                cutOffDatetime = cd['cutOffDatetime']
                describe = cd['describe']
                seller = Seller.objects.get(id=id)
                if int(preferential_type) > 0 and int(preferential_type) < 3:
                    preferential = Preferential()
                    goods.isPreferential = '是'
                    goods.save()
                    preferential.goods = goods
                    preferential.seller = seller
                    preferential.preferential_type = preferential_type
                    preferential.enoughNumber = enoughNumber
                    preferential.minusNumber = minusNumber
                    preferential.discount = discount
                    preferential.cutOffDatetime = cutOffDatetime
                    preferential.describe = describe
                    preferential.save()
        else:
            form = AddPreferentialForm()
            
        return render(request, 'seller/addpreferential.html', {"form": form})        
    
    else:
        form = LoginForm()

templates/seller/addgoods.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}添加商品{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>请输入商品信息（如果想给此商品设置优惠券请到“添加优惠券”功能中设置）</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="添加"></p>
		</form>
		{% endblock %}
	</body>
</html>

templates/seller/addpreferential.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}添加优惠券{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>优惠券填写说明</p>
		<ul>
			<li>优惠类型分为满减、打几折、满足多少后打几折三种类型</li>
			<li>如果是满减或打折，则在enoughNumber选项填满多少，不是则填0</li>
			<li>如果是满减，则在minusNumber选项填减多少，不是则填0</li>
			<li>如果是打折，则此填打折小数（打8折填写0.8），不是则填写1</li>
		</ul>
		<p>请输入优惠券信息</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="添加"></p>
		</form>
		{% endblock %}
	</body>
</html>

templates/seller/addtag.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}添加商品标签{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>请输入商品标签</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="添加"></p>
		</form>
		{% endblock %}
	</body>
</html>

templates/seller/addtypes.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}添加商品类型{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>请输入商品类型</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="添加"></p>
		</form>
		{% endblock %}
	</body>
</html>

templates/seller/goodschangemessage.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}修改商品信息{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>请输入商品信息（如果想给此商品设置优惠券请到“添加优惠券”功能中设置）</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="修改"></p>
		</form>
		{% endblock %}
	</body>
</html>

templates/seller/goodsdetail.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}我的所有上架商品 | 详细{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		{% if goods.goodsImage %}
			<img src="{{ MEDIA_URL }}{{ goods.goodsImage }}" alt="photo" width=50 height=50>
		{% else %}
			<p>此商品还没有上传图片！！</p>
		{% endif %}
		<h3>{{ goods.name }}</h3>
		<p>价格：{{ goods.price }} 元</p>
		<p>数量：{{ goods.number }} 个</p>
		<p>颜色：{{ goods.color }}</p>
		<p>上架时间：{{ goods.time }}</p>
		<p>商品描述：{{ goods.describe }}</p>
		{% if goods.isPreferential == '否' %}
			<p>此商品的优惠：没有</p>
		{% else %}
			<p>此商品的优惠：</p>
			<ul>
				{% for preferential in preferentials %}
					{% if preferential.preferential_type is 1 %}
						<li>
							此商品满 {{ preferential.enoughNumber }} 元减 {{ preferential.minusNumber }} 元<br>
							截至日期： {{ preferential.cutOffDatetime }}<br>
							店家的描述：{{ preferential.describe }}
						</li>
					{% elif preferential.preferential_type is 2 %}
						<li>
							此商品打 {{ preferential.discount }} 折<br>
							截至日期是 {{ preferential.cutOffDatetime }}<br>
							店家的描述是 {{ preferential.describe }}
						</li>
					{% else %}
						<li>
							此商品满 {{ preferential.enoughNumber }} 元
							打 {{ preferential.discount }} 折<br>
							截至日期是 {{ preferential.cutOffDatetime }}<br>
							店家的描述是 {{ preferential.describe }}
						</li>
					{% endif %}
				{% endfor %}
			</ul>
		{% endif %}
		<hr>
		<a href="{% url 'seller:seller_goodsChangeMessage' goods.pk %}"><h3>修改商品相关信息</h3></a>
		{% endblock %}
	</body>
</html>

templates/seller/goodslist.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}我的所有上架商品 | 列表{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
			<h2>我的所有上架商品 | 列表</h2>
			<hr>
			{% for goods in goodses %}
				<a href="{% url 'seller:seller_goodsDetail' goods.pk %}"><h3>{{ goods.name }}</h3></a>
				<p>价格：{{ goods.price }} 元</p>
				<p>数量：{{ goods.number }} 个</p>
				<p>颜色：{{ goods.color }}</p>
				<p>上架时间：{{ goods.time }}</p>
				<p>是否有优惠：{{ goods.isPreferential }}</p>
				<hr>
			{% endfor %}
		{% endblock %}
	</body>
</html>

templates/seller/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}卖家登录{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>请输入你的账号密码进行登录</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="登录"></p>
		</form>
		{% endblock %}
	</body>
</html>

templates/seller/persional.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}个人中心{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<img src="{{ MEDIA_URL }}{{ seller.photo }}" alt="photo" width=50 height=50>
		<p>姓    名：{{ seller.name }}</p>
		<p>性    别：{{ seller.sex }}</p>
		<p>年    龄：{{ seller.age }}</p>
		<p>电话号码：{{ seller.phone }}</p>
		<p>邮    箱：{{ seller.email }}</p>
		<p>地    址：{{ seller.address }}</p>
		<p>注册日期：{{ seller.registerDate }}</p>
		<a href="{% url 'seller:seller_addGoods' seller.pk %}">添加商品</a>
		<a href="{% url 'seller:seller_addTag' seller.pk %}">添加商品标签</a>
		<a href="{% url 'seller:seller_addTypes' seller.pk %}">添加商品类别</a>
		<a href="{% url 'seller:seller_addPreferential' seller.pk %}">添加商品优惠券</a>
		<a href="{% url 'seller:seller_allGoods' seller.pk %}">我的所有上架商品</a>
		{% endblock %}
	</body>
</html>

templates/seller/register.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
	    <title>
			{% block title %}卖家注册{% endblock %}
		</title>
	</head>
	<body>
		{% block context %}
		<p>请输入你的信息进行注册</p>
		<form action="" method="post" enctype="multipart/form-data">
			{{ form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="登录"></p>
		</form>
		{% endblock %}
	</body>
</html>